spring:
  application:
    name: WarehouseManager
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_manager
    username: postgres
    password: linh191004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  jwt:
    secret: N2hLMk5Vek4vVzI4a0F4ZzM4MWhFdXVuQmNwY3ZzWjJ2L2Q2Q3dOeDN4b1Q4Vk1MWQ==
    expiration-ms: 86400000
